site_name: PhoneInfoga
repo_name: 'sundowndev/phoneinfoga'
repo_url: 'https://github.com/sundowndev/phoneinfoga'
site_description: 'Advanced information gathering & OSINT tool for phone numbers.'
site_author: 'Sundowndev'
copyright: 'PhoneInfoga was developed by sundowndev and is licensed under GPL-3.0.'
nav:
  - 'Introduction': index.md
  - 'Installation': install.md
  - 'Usage': usage.md
  - 'Scanners': scanners.md
  - 'Formatting phone numbers': formatting.md
  - 'Go module usage': go-module-usage.md
  - 'Resources': resources.md
  - 'Contribute': contribute.md
theme:
  name: material
  logo: './images/logo_white.svg'
  favicon: './images/logo.svg'
  palette:
    primary: 'blue grey'
    accent: 'brown'
  features:
    - content.tabs.link
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/sundowndev/phoneinfoga'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/sundowndev'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - minify:
      minify_html: true
