name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.x
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.18.x

      - name: Building static assets
        run: (cd client && yarn && yarn build)

      - name: Build
        run: |
          go generate ./...
          go build -v .

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.24.0
          ./bin/golangci-lint run -D errcheck

      - name: Test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          curl -s -o codecov https://codecov.io/bash \
            && VERSION=$(grep 'VERSION=\".*\"' codecov | cut -d'"' -f2) \
            && shasum -a 512 -c --ignore-missing <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA512SUM)
          chmod +x codecov
          go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
          ./codecov
